### ISSUE TITLE
BNC Playback Buffer

### ISSUE THREAD

**Issue by ds4112** [ConversationDevelopers/conversation#92]
please allow option to disable conversations app chat history, duplicated when connecting to bnc w/ playback buffer. 

can lead to flood

**Comment by foldericon** [comment]
Are you using ZNC or anything else? Since there shouldn't be any duplicates if you're on newest ZNC version and your system times are in sync.

**Comment by foldericon** [comment]
Sorry i forgot, you also need this module https://github.com/jpnurmi/znc-playback
Feel free to join #znc or #conversation on freenode if you need any help setting it up.

**Comment by ds4112** [comment]
used clearall connect command to fix

**Comment by foldericon** [comment]
¯\_(ツ)_/¯
